bfs: update scripts to follow new partition format
As per the new partition format, application, micrcode images and cpt
kernel module will be in different partition than Image and rootfs.

This is to minimize the changes to be effected for any update in
application or microcode images.

Update the scripts to use the /mnt/app as the new location to application.

Update the post build script to copy the microcode images to the
lc_service/mc/mrvl/cpt02.

Update the kernel config to built cpt driver as module.
This is required to load the firmware from application partition.

Update the lc init script to mount the application partition before
launching the lc_service.

Update the lc_env script to load the cpt kernel module before creating
the cpt VFs.

Signed-off-by: Vidya Sagar Velumuri <vvelumuri@marvell.com>
Change-Id: I550d89af8731372cc78a6418bd6f3a7766f8906a
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/dataplane/dpu-offload/+/155573
Tested-by: sa_ip-toolkits-Jenkins <sa_ip-toolkits-jenkins@marvell.com>
Reviewed-by: Anoob Joseph <anoobj@marvell.com>
Reviewed-by: Vamsi Krishna Attunuru <vattunuru@marvell.com>
Reviewed-by: Jerin Jacob <jerinj@marvell.com>

diff --git a/bfs/board/octeon_cn9k/lc/rootfs_overlay/etc/init.d/S99lc b/bfs/board/octeon_cn9k/lc/rootfs_overlay/etc/init.d/S99lc
--- a/bfs/board/octeon_cn9k/lc/rootfs_overlay/etc/init.d/S99lc
+++ b/bfs/board/octeon_cn9k/lc/rootfs_overlay/etc/init.d/S99lc
@@ -3,12 +3,40 @@
 # Copyright (c) 2025 Marvell.
 
 DAEMON="lc_service.sh"
-EXEC="/root/lc_service/scripts/$DAEMON"
+EXEC="/scripts/$DAEMON"
 PIDFILE="/var/run/$DAEMON.pid"
 
 start() {
+	# Check if the booting is from mmc or spi.
+	# application source will be based on which boot
+	cmdline=$(cat /proc/cmdline)
+
+
+	# Mount the appropriate partition based on app_env
+	if echo "$cmdline" | grep -q "root="; then
+		if [ ! -d /mnt/app ]; then
+			mkdir -p /mnt/app
+		fi
+
+		app_env=$(fw_printenv -c /etc/fw_mmc_env.config app_env | cut -d'=' -f2)
+		if [ -z "$app_env" ]; then
+			echo "FAIL: app_env not set"
+			exit 1
+		elif [ "$app_env" = "p3" ]; then
+			mount /dev/mmcblk0p3 /mnt/app
+		elif [ "$app_env" = "p5" ]; then
+			mount /dev/mmcblk0p5 /mnt/app
+		else
+			echo "FAIL: Unknown app_env value"
+			exit 1
+		fi
+		APP_HOME="/mnt/app/lc_service"
+	else
+		APP_HOME="/root/lc_service"
+	fi
+
 	printf 'Starting %s: ' "$DAEMON"
-	start-stop-daemon --start --background --make-pidfile -p "$PIDFILE" --exec "$EXEC"
+	start-stop-daemon --start --background --make-pidfile -p "$PIDFILE" --exec "$APP_HOME$EXEC" -- "$APP_HOME"
 	status=$?
 	if [ "$status" -eq 0 ]; then
 		echo "OK"
